# general settings
name: train_HAT-S_v4.2_SRx4_from_scratch_europe-small-100to25_seed0
model_type: HATBiomassModel
scale: 4
num_gpu: auto
# find_unused_parameters: true
manual_seed: 0

tile: # use the tile mode for limited GPU memory when testing.
  tile_size: 64 # the higher, the more utilized GPU memory and the less performance change against the full image. must be an integer multiple of the window size.
  tile_pad: 0

# dataset and data loader settings
datasets:
  train:
    name: europe-small-100-25m-train
    type: PairedBiomassDataset
    dataroot_gt: /mnt/gpid08/datasets/biomassa/europe-small/patches1920x1920/2010_25m_sub/train
    dataroot_lq: /mnt/gpid08/datasets/biomassa/europe-small/patches1920x1920/2010_100m_sub/train
    meta_info_file: /home/usuaris/imatge/laia.albors/TASKS/GlobalBiomass/repos/biomsharp/biomsharp/data/meta_info/meta_info_europe-small-25m_GT.txt
    io_backend:
      type: disk

    gt_size: 256 #256/64/128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 3 #6 #6
    batch_size_per_gpu: 4 #12 #4/8 #6 amb gpus de 24
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: europe-small-100-25m-valid
    type: PairedBiomassDataset
    dataroot_gt: /mnt/gpid08/datasets/biomassa/europe-small/patches1920x1920/2010_25m_sub/validation
    dataroot_lq: /mnt/gpid08/datasets/biomassa/europe-small/patches1920x1920/2010_100m_sub/validation
    io_backend:
      type: disk


# network structures
network_g:
  type: HAT
  upscale: 4
  in_chans: 1
  img_size: 64
  window_size: 16
  compress_ratio: 24
  squeeze_factor: 24
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 144 #84
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 5e-4 #2e-4 #1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [80000, 110000, 150000, 200000] #[125000, 200000, 225000, 240000]
    gamma: 0.5

  total_iter: 500000 #1000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 2000 #5e3 #1e4 #2e4
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr_biomass
      crop_border: 4
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim_biomass
      crop_border: 4
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher
    mse:
      type: calculate_mse
      crop_border: 4
      test_y_channel: false
      better: lower  # the lower, the better
    rmse:
      type: calculate_rmse
      crop_border: 4
      test_y_channel: false
      better: lower
    mae:
      type: calculate_mae
      crop_border: 4
      test_y_channel: false
      better: lower

# logging settings
logger:
  print_freq: 200 #400
  save_checkpoint_freq: !!float 2000 #5e3 #1e4 #2e4
  use_tb_logger: true
  wandb:
    project: biomsharp-experiments #~
    resume_id: 3fp522sl #~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

