# general settings
name: train_BIOSHARP_v9.4_HAT-S_SRx4_from_scratch_europe-small-100to25_patches1920x1920_seed124
model_type: BIOSHARPModel
scale: 4
num_gpu: auto
manual_seed: 124

tile: # use the tile mode for limited GPU memory when testing.
  tile_size: 64 # the higher, the more utilized GPU memory and the less performance change against the full image. must be an integer multiple of the window size.
  tile_pad: 0

# dataset and data loader settings
datasets:
  train:
    name: europe-small-100-25m-patches1920x1920-train
    type: TripletImageDataset
    dataroot_gt: /mnt/gpid08/datasets/biomassa/europe-small/patches1920x1920/2010_25m_sub/train
    dataroot_lq: /mnt/gpid08/datasets/biomassa/europe-small/patches1920x1920/2010_100m_sub/train
    dataroot_op: /mnt/gpid08/datasets/biomassa/europe-small/patches1920x1920/2010_sentinel_25m_sub/train  # 2010_sentinel_B5_B6_B7_B8A_25m_sub / 2010_sentinel_B11_B8_B2_B4_25m_sub / 2010_sentinel_B11_B8_B2_25m_sub / 2010_sentinel_25m_sub / 2010_sentinel_Ball_25m_sub / 2010_sentinel_B8_B4_25m_sub
    meta_info_file: /home/usuaris/imatge/laia.albors/TASKS/GlobalBiomass/BIOSHARP/HAT/hat/data/meta_info/meta_info_europe-small-25m_GT.txt
    io_backend:
      type: disk

    gt_size: 256 #256/64/128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 1 #4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: europe-small-100-25m-patches1920x1920-valid
    type: TripletImageDataset
    dataroot_gt: /mnt/gpid08/datasets/biomassa/europe-small/patches1920x1920/2010_25m_sub/validation
    dataroot_lq: /mnt/gpid08/datasets/biomassa/europe-small/patches1920x1920/2010_100m_sub/validation
    dataroot_op: /mnt/gpid08/datasets/biomassa/europe-small/patches1920x1920/2010_sentinel_25m_sub/validation  # 2010_sentinel_B11_B8_B2_25m_sub / 2010_sentinel_25m_sub
    io_backend:
      type: disk


# network structures
network_g:
  type: BIOSHARP
  sentinel_channels: 3 #2/3/4/10
  upscale: 4
  in_chans: 1
  img_size: 64
  window_size: 16
  compress_ratio: 24
  squeeze_factor: 24
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6]
  embed_dim: 84
  num_heads: [6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [125000, 200000, 225000, 240000]
    gamma: 0.5

  total_iter: 1000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 2e4
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    mse:
      type: calculate_mse
      crop_border: 4
      test_y_channel: true
      better: lower  # the lower, the better
    rmse:
      type: calculate_rmse
      crop_border: 4
      test_y_channel: true
      better: lower
    mae:
      type: calculate_mae
      crop_border: 4
      test_y_channel: true
      better: lower

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
